'''
Created on 2018年12月8日

@author: Administrator
'''

#TASK ID defination
TUP_TASK_ID_NULL        = 0
TUP_TASK_ID_MAIN_ENTRY  = 1
TUP_TASK_ID_VMCONSL     = 2
TUP_TASK_ID_TIMER       = 3
TUP_TASK_ID_CALIB       = 10
TUP_TASK_ID_CTRL_SCHD   = 11
TUP_TASK_ID_GPAR        = 12
TUP_TASK_ID_MENG        = 13
TUP_TASK_ID_VISION      = 14
TUP_TASK_ID_MOTO        = 15
TUP_TASK_ID_UI_MAIN     = 20
TUP_TASK_ID_UI_CALIB    = 21
TUP_TASK_ID_UI_GPAR     = 22
TUP_TASK_ID_UI_MENG     = 23
TUP_TASK_ID_UI_BROW     = 24

TUP_TASK_ID_TEST        = 99

#Message ID defination
TUP_MSGID_NULL          = 0
TUP_MSGID_INIT          = 1
TUP_MSGID_TIME_OUT      = 2
TUP_MSGID_RESTART       = 3
TUP_MSGID_GEN_TRIG      = 4
TUP_MSGID_TRACE         = 5
TUP_MSGID_TEST          = 6

#界面相关的切换消息
TUP_MSGID_MAIN_UI_SWITCH= 20
TUP_MSGID_CALIB_UI_SWITCH= 21
TUP_MSGID_GPAR_UI_SWITCH = 22
TUP_MSGID_MENG_UI_SWITCH= 23
TUP_MSGID_BROW_UI_SWITCH= 24

#马达运动和反馈消息
TUP_MSGID_NORM_MOTO_BACK_ZERO   = 30
TUP_MSGID_NORM_MOTO_MOVE_START  = 31
TUP_MSGID_NORM_MOTO_MOVE_HOLEN  = 32
TUP_MSGID_CALIB_MOTO_MV_STEP    = 33
TUP_MSGID_CALIB_MOTO_FM_STEP    = 34
TUP_MSGID_MENG_MOTO_COMMAND     = 35
TUP_MSGID_MENG_MOTO_CMD_FB      = 36

#视频操控和反馈消息
TUP_MSGID_PIC_CAP_REQ       = 40
TUP_MSGID_PIC_CAP_RESP      = 41
TUP_MSGID_PIC_CLFY_REQ      = 42
TUP_MSGID_PIC_CLFY_RESP     = 43
TUP_MSGID_PIC_REFRESH_PAR   = 44















