'''
Created on 2018年12月8日

@author: Administrator
'''

#TASK ID defination
#同步申明名字
TUP_TASK_NBR_MAX = 100
TUP_TASK_NAME = ['' for i in range(TUP_TASK_NBR_MAX)]
TUP_TASK_ID_NULL        = 0;    TUP_TASK_NAME[TUP_TASK_ID_NULL] = "TK_NULL"
TUP_TASK_ID_TUPCONSL    = 1;    TUP_TASK_NAME[TUP_TASK_ID_TUPCONSL] = "TK_CONSL"
TUP_TASK_ID_VMCONSL     = 2;    TUP_TASK_NAME[TUP_TASK_ID_VMCONSL] = "TK_VM_CONSL"
TUP_TASK_ID_CALIB       = 10;   TUP_TASK_NAME[TUP_TASK_ID_CALIB] = "TK_CALIB"
TUP_TASK_ID_CTRL_SCHD   = 11;   TUP_TASK_NAME[TUP_TASK_ID_CTRL_SCHD] = "TK_CTRL_SCHD"
TUP_TASK_ID_GPAR        = 12;   TUP_TASK_NAME[TUP_TASK_ID_GPAR] = "TK_GPAR"
TUP_TASK_ID_MENG        = 13;   TUP_TASK_NAME[TUP_TASK_ID_MENG] = "TK_MENG"
TUP_TASK_ID_VISION      = 14;   TUP_TASK_NAME[TUP_TASK_ID_VISION] = "TK_VISION"
TUP_TASK_ID_MOTO        = 15;   TUP_TASK_NAME[TUP_TASK_ID_MOTO] = "TK_MOTO"
TUP_TASK_ID_UI_MAIN     = 20;   TUP_TASK_NAME[TUP_TASK_ID_UI_MAIN] = "TK_UI_MAIN"
TUP_TASK_ID_UI_CALIB    = 21;   TUP_TASK_NAME[TUP_TASK_ID_UI_CALIB] = "TK_UI_CALIB"
TUP_TASK_ID_UI_GPAR     = 22;   TUP_TASK_NAME[TUP_TASK_ID_UI_GPAR] = "TK_UI_GPAR"
TUP_TASK_ID_UI_MENG     = 23;   TUP_TASK_NAME[TUP_TASK_ID_UI_MENG] = "TK_UI_MENG"
TUP_TASK_ID_UI_BROW     = 24;   TUP_TASK_NAME[TUP_TASK_ID_UI_BROW] = "TK_UI_BROW"
TUP_TASK_ID_TEST        = 99;   TUP_TASK_NAME[TUP_TASK_ID_TEST] = "TK_TEST"

#Message ID defination
TUP_MSG_ID_NBR_MAX = 500
TUP_MID_NAME = ['' for i in range(TUP_MSG_ID_NBR_MAX)]
#BASIC ONES
TUP_MSGID_NULL          = 0;    TUP_MID_NAME[TUP_MSGID_NULL] = "MID_NULL"
TUP_MSGID_INIT          = 1;    TUP_MID_NAME[TUP_MSGID_INIT] = "MID_INIT"
TUP_MSGID_RESTART       = 2;    TUP_MID_NAME[TUP_MSGID_RESTART] = "MID_RESTART"
TUP_MSGID_GEN_TRIG      = 3;    TUP_MID_NAME[TUP_MSGID_GEN_TRIG] = "MID_GEN_TRIG"
TUP_MSGID_TRACE         = 4;    TUP_MID_NAME[TUP_MSGID_TRACE] = "MID_TRACE"
TUP_MSGID_TEST          = 5;    TUP_MID_NAME[TUP_MSGID_TEST] = "MID_TEST"

#界面相关的切换消息
TUP_MSGID_MAIN_UI_SWITCH        = 20;    TUP_MID_NAME[TUP_MSGID_MAIN_UI_SWITCH] = "MID_MAIN_UI_SWITCH"
TUP_MSGID_CALIB_UI_SWITCH       = 21;    TUP_MID_NAME[TUP_MSGID_CALIB_UI_SWITCH] = "MID_CALIB_UI_SWITCH"
TUP_MSGID_GPAR_UI_SWITCH        = 22;    TUP_MID_NAME[TUP_MSGID_GPAR_UI_SWITCH] = "MID_GPAR_UI_SWITCH"
TUP_MSGID_MENG_UI_SWITCH        = 23;    TUP_MID_NAME[TUP_MSGID_MENG_UI_SWITCH] = "MID_MENG_UI_SWITCH"
TUP_MSGID_BROW_UI_SWITCH        = 24;    TUP_MID_NAME[TUP_MSGID_BROW_UI_SWITCH] = "MID_BROW_UI_SWITCH"

#马达运动和反馈消息
TUP_MSGID_NORM_MOTO_BACK_ZERO   = 30;    TUP_MID_NAME[TUP_MSGID_NORM_MOTO_BACK_ZERO] = "MID_NORM_MOTO_BACK_ZERO"
TUP_MSGID_NORM_MOTO_STOP        = 33;    TUP_MID_NAME[TUP_MSGID_NORM_MOTO_STOP] = "MID_NORM_MOTO_STOP"

#视频操控和反馈消息
TUP_MSGID_PIC_CAP_REQ           = 40;    TUP_MID_NAME[TUP_MSGID_PIC_CAP_REQ] = "MID_PIC_CAP_REQ"
TUP_MSGID_PIC_CAP_RESP          = 41;    TUP_MID_NAME[TUP_MSGID_PIC_CAP_RESP] = "MID_PIC_CAP_RESP"
TUP_MSGID_PIC_CLFY_REQ          = 42;    TUP_MID_NAME[TUP_MSGID_PIC_CLFY_REQ] = "MID_PIC_CLFY_REQ"
TUP_MSGID_PIC_CLFY_RESP         = 43;    TUP_MID_NAME[TUP_MSGID_PIC_CLFY_RESP] = "MID_PIC_CLFY_RESP"
TUP_MSGID_PIC_REFRESH_PAR       = 44;    TUP_MID_NAME[TUP_MSGID_PIC_REFRESH_PAR] = "MID_PIC_REFRESH_PAR"

#GPAR控制消息
TUP_MSGID_GPAR_INIT_INF         = 50;    TUP_MID_NAME[TUP_MSGID_GPAR_INIT_INF] = "MID_GPAR_INIT_INF"
TUP_MSGID_GPAR_PIC_TRAIN_REQ    = 51;    TUP_MID_NAME[TUP_MSGID_GPAR_PIC_TRAIN_REQ] = "MID_GPAR_PIC_TRAIN_REQ"
TUP_MSGID_GPAR_PIC_TRAIN_RESP   = 52;    TUP_MID_NAME[TUP_MSGID_GPAR_PIC_TRAIN_RESP] = "MID_GPAR_PIC_TRAIN_RESP"
TUP_MSGID_GPAR_CLOSE_REQ        = 53;    TUP_MID_NAME[TUP_MSGID_GPAR_CLOSE_REQ] = "MID_GPAR_CLOSE_REQ"

#CALIB控制消息
TUP_MSGID_CALIB_OPEN_REQ        = 60;    TUP_MID_NAME[TUP_MSGID_CALIB_OPEN_REQ] = "MID_CALIB_OPEN_REQ"
TUP_MSGID_CALIB_CLOSE_REQ       = 61;    TUP_MID_NAME[TUP_MSGID_CALIB_CLOSE_REQ] = "MID_CALIB_CLOSE_REQ"
TUP_MSGID_CALIB_VDISP_REQ       = 62;    TUP_MID_NAME[TUP_MSGID_CALIB_VDISP_REQ] = "MID_CALIB_VDISP_REQ"
TUP_MSGID_CALIB_VDISP_RESP      = 63;    TUP_MID_NAME[TUP_MSGID_CALIB_VDISP_RESP] = "MID_CALIB_VDISP_RESP"
TUP_MSGID_CALIB_PIC_CAP_HOLEN   = 64;    TUP_MID_NAME[TUP_MSGID_CALIB_PIC_CAP_HOLEN] = "MID_CALIB_PIC_CAP_HOLEN"
TUP_MSGID_CALIB_MOMV_DIR_REQ    = 70;    TUP_MID_NAME[TUP_MSGID_CALIB_MOMV_DIR_REQ] = "MID_CALIB_MOMV_DIR_REQ"
TUP_MSGID_CALIB_MOMV_DIR_RESP   = 71;    TUP_MID_NAME[TUP_MSGID_CALIB_MOMV_DIR_RESP] = "MID_CALIB_MOMV_DIR_RESP"
TUP_MSGID_CALIB_MOFM_DIR_REQ    = 72;    TUP_MID_NAME[TUP_MSGID_CALIB_MOFM_DIR_REQ] = "MID_CALIB_MOFM_DIR_REQ"
TUP_MSGID_CALIB_MOFM_DIR_RESP   = 73;    TUP_MID_NAME[TUP_MSGID_CALIB_MOFM_DIR_RESP] = "MID_CALIB_MOFM_DIR_RESP"
TUP_MSGID_CALIB_RIGHT_UP_SET    = 74;    TUP_MID_NAME[TUP_MSGID_CALIB_RIGHT_UP_SET] = "MID_CALIB_RIGHT_UP_SET"
TUP_MSGID_CALIB_LEFT_DOWN_SET   = 75;    TUP_MID_NAME[TUP_MSGID_CALIB_LEFT_DOWN_SET] = "MID_CALIB_LEFT_DOWN_SET"
TUP_MSGID_CALIB_MOMV_START      = 76;    TUP_MID_NAME[TUP_MSGID_CALIB_MOMV_START] = "MID_CALIB_MOMV_START"
TUP_MSGID_CALIB_MOMV_HOLEN      = 77;    TUP_MID_NAME[TUP_MSGID_CALIB_MOMV_HOLEN] = "MID_CALIB_MOMV_HOLEN"
TUP_MSGID_CALIB_PILOT_START     = 78;    TUP_MID_NAME[TUP_MSGID_CALIB_PILOT_START] = "MID_CALIB_PILOT_START"
TUP_MSGID_CALIB_PILOT_STOP      = 79;    TUP_MID_NAME[TUP_MSGID_CALIB_PILOT_STOP] = "MID_CALIB_PILOT_STOP"

#MENG控制消息
TUP_MSGID_MENG_CLOSE_REQ        = 90;    TUP_MID_NAME[TUP_MSGID_MENG_CLOSE_REQ] = "MID_MENG_CLOSE_REQ"
TUP_MSGID_MENG_MOTO_COMMAND     = 91;    TUP_MID_NAME[TUP_MSGID_MENG_MOTO_COMMAND] = "MID_MENG_MOTO_COMMAND"
TUP_MSGID_MENG_MOTO_CMD_FB      = 92;    TUP_MID_NAME[TUP_MSGID_MENG_MOTO_CMD_FB] = "MID_MENG_MOTO_CMD_FB"








