# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cebsMengform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cebsMengForm(object):
    def setupUi(self, cebsMengForm):
        cebsMengForm.setObjectName("cebsMengForm")
        cebsMengForm.resize(1185, 643)
        self.label_meng_cmd_sel = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_cmd_sel.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_meng_cmd_sel.setObjectName("label_meng_cmd_sel")
        self.listWidget_meng_cmd = QtWidgets.QListWidget(cebsMengForm)
        self.listWidget_meng_cmd.setGeometry(QtCore.QRect(20, 30, 421, 231))
        self.listWidget_meng_cmd.setObjectName("listWidget_meng_cmd")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_meng_cmd.addItem(item)
        self.label_meng_par1 = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_par1.setGeometry(QtCore.QRect(20, 270, 54, 12))
        self.label_meng_par1.setObjectName("label_meng_par1")
        self.label_meng_par2 = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_par2.setGeometry(QtCore.QRect(130, 270, 54, 12))
        self.label_meng_par2.setObjectName("label_meng_par2")
        self.label_meng_par3 = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_par3.setGeometry(QtCore.QRect(240, 270, 54, 12))
        self.label_meng_par3.setObjectName("label_meng_par3")
        self.label_meng_par4 = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_par4.setGeometry(QtCore.QRect(350, 270, 54, 12))
        self.label_meng_par4.setObjectName("label_meng_par4")
        self.pushButton_meng_cmd_send = QtWidgets.QPushButton(cebsMengForm)
        self.pushButton_meng_cmd_send.setGeometry(QtCore.QRect(320, 330, 121, 51))
        self.pushButton_meng_cmd_send.setObjectName("pushButton_meng_cmd_send")
        self.textEdit_meng_trace_log = QtWidgets.QTextEdit(cebsMengForm)
        self.textEdit_meng_trace_log.setGeometry(QtCore.QRect(460, 30, 691, 401))
        self.textEdit_meng_trace_log.setObjectName("textEdit_meng_trace_log")
        self.label_meng_trace_log = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_trace_log.setGeometry(QtCore.QRect(460, 10, 54, 12))
        self.label_meng_trace_log.setObjectName("label_meng_trace_log")
        self.pushButton_ctrl_giveup_3 = QtWidgets.QPushButton(cebsMengForm)
        self.pushButton_ctrl_giveup_3.setGeometry(QtCore.QRect(1070, 440, 81, 41))
        self.pushButton_ctrl_giveup_3.setObjectName("pushButton_ctrl_giveup_3")
        self.pushButton_ctrl_giveup_4 = QtWidgets.QPushButton(cebsMengForm)
        self.pushButton_ctrl_giveup_4.setGeometry(QtCore.QRect(970, 440, 81, 41))
        self.pushButton_ctrl_giveup_4.setObjectName("pushButton_ctrl_giveup_4")
        self.lineEdit_meng_par1 = QtWidgets.QLineEdit(cebsMengForm)
        self.lineEdit_meng_par1.setGeometry(QtCore.QRect(20, 290, 91, 20))
        self.lineEdit_meng_par1.setObjectName("lineEdit_meng_par1")
        self.lineEdit_meng_par2 = QtWidgets.QLineEdit(cebsMengForm)
        self.lineEdit_meng_par2.setGeometry(QtCore.QRect(130, 290, 91, 20))
        self.lineEdit_meng_par2.setObjectName("lineEdit_meng_par2")
        self.lineEdit_meng_par3 = QtWidgets.QLineEdit(cebsMengForm)
        self.lineEdit_meng_par3.setGeometry(QtCore.QRect(240, 290, 91, 20))
        self.lineEdit_meng_par3.setObjectName("lineEdit_meng_par3")
        self.lineEdit_meng_par4 = QtWidgets.QLineEdit(cebsMengForm)
        self.lineEdit_meng_par4.setGeometry(QtCore.QRect(350, 290, 91, 20))
        self.lineEdit_meng_par4.setObjectName("lineEdit_meng_par4")
        self.lineEdit_meng_cmd_par = QtWidgets.QLineEdit(cebsMengForm)
        self.lineEdit_meng_cmd_par.setGeometry(QtCore.QRect(320, 410, 121, 20))
        self.lineEdit_meng_cmd_par.setObjectName("lineEdit_meng_cmd_par")
        self.label_meng_cmd_par = QtWidgets.QLabel(cebsMengForm)
        self.label_meng_cmd_par.setGeometry(QtCore.QRect(320, 390, 81, 16))
        self.label_meng_cmd_par.setObjectName("label_meng_cmd_par")

        self.retranslateUi(cebsMengForm)
        self.pushButton_meng_cmd_send.clicked.connect(cebsMengForm.slot_meng_cmd_send)
        self.pushButton_ctrl_giveup_3.clicked.connect(cebsMengForm.slot_meng_trace_clear)
        self.pushButton_ctrl_giveup_4.clicked.connect(cebsMengForm.slot_meng_compl)
        QtCore.QMetaObject.connectSlotsByName(cebsMengForm)

    def retranslateUi(self, cebsMengForm):
        _translate = QtCore.QCoreApplication.translate
        cebsMengForm.setWindowTitle(_translate("cebsMengForm", "工程模式"))
        self.label_meng_cmd_sel.setText(_translate("cebsMengForm", "命令选择"))
        __sortingEnabled = self.listWidget_meng_cmd.isSortingEnabled()
        self.listWidget_meng_cmd.setSortingEnabled(False)
        item = self.listWidget_meng_cmd.item(0)
        item.setText(_translate("cebsMengForm", "设备握手（shake_hand）"))
        item = self.listWidget_meng_cmd.item(1)
        item.setText(_translate("cebsMengForm", "设置工作模式（set_wk_mode）"))
        item = self.listWidget_meng_cmd.item(2)
        item.setText(_translate("cebsMengForm", "设置加速度（set_acc）"))
        item = self.listWidget_meng_cmd.item(3)
        item.setText(_translate("cebsMengForm", "设置减速度（set_deacc）"))
        item = self.listWidget_meng_cmd.item(4)
        item.setText(_translate("cebsMengForm", "设置一圈步伐（set_pules_per_cycle）"))
        item = self.listWidget_meng_cmd.item(5)
        item.setText(_translate("cebsMengForm", "设置移动速度（set_mv_spd）"))
        item = self.listWidget_meng_cmd.item(6)
        item.setText(_translate("cebsMengForm", "设置归零速度（set_zero_spd）"))
        item = self.listWidget_meng_cmd.item(7)
        item.setText(_translate("cebsMengForm", "设置归零加速度（set_zero_acc）"))
        item = self.listWidget_meng_cmd.item(8)
        item.setText(_translate("cebsMengForm", "设置靠边后退步伐（set_int_steps）"))
        item = self.listWidget_meng_cmd.item(9)
        item.setText(_translate("cebsMengForm", "移动步伐（mv_pules）"))
        item = self.listWidget_meng_cmd.item(10)
        item.setText(_translate("cebsMengForm", "移动速度（mv_spd）"))
        item = self.listWidget_meng_cmd.item(11)
        item.setText(_translate("cebsMengForm", "归零（mv_zero）"))
        item = self.listWidget_meng_cmd.item(12)
        item.setText(_translate("cebsMengForm", "立即停止（stop_imd）"))
        item = self.listWidget_meng_cmd.item(13)
        item.setText(_translate("cebsMengForm", "缓慢停止（stop_nor)"))
        item = self.listWidget_meng_cmd.item(14)
        item.setText(_translate("cebsMengForm", "查询激活状态（inq_enable）"))
        item = self.listWidget_meng_cmd.item(15)
        item.setText(_translate("cebsMengForm", "查询运行状态（inq_run）"))
        item = self.listWidget_meng_cmd.item(16)
        item.setText(_translate("cebsMengForm", "查询一般状态（inq_status）"))
        item = self.listWidget_meng_cmd.item(17)
        item.setText(_translate("cebsMengForm", "测试脉冲数（test_pules)"))
        item = self.listWidget_meng_cmd.item(18)
        item.setText(_translate("cebsMengForm", "设置限位器触发迟滞（set_exti_delay_time)"))
        self.listWidget_meng_cmd.setSortingEnabled(__sortingEnabled)
        self.label_meng_par1.setText(_translate("cebsMengForm", "参数1"))
        self.label_meng_par2.setText(_translate("cebsMengForm", "参数2"))
        self.label_meng_par3.setText(_translate("cebsMengForm", "参数3"))
        self.label_meng_par4.setText(_translate("cebsMengForm", "参数4"))
        self.pushButton_meng_cmd_send.setText(_translate("cebsMengForm", "命令发送"))
        self.textEdit_meng_trace_log.setHtml(_translate("cebsMengForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TRACE LOG</p></body></html>"))
        self.label_meng_trace_log.setText(_translate("cebsMengForm", "信息窗口"))
        self.pushButton_ctrl_giveup_3.setText(_translate("cebsMengForm", "清除"))
        self.pushButton_ctrl_giveup_4.setText(_translate("cebsMengForm", "完成"))
        self.lineEdit_meng_par1.setText(_translate("cebsMengForm", "0"))
        self.lineEdit_meng_par2.setText(_translate("cebsMengForm", "0"))
        self.lineEdit_meng_par3.setText(_translate("cebsMengForm", "0"))
        self.lineEdit_meng_par4.setText(_translate("cebsMengForm", "0"))
        self.lineEdit_meng_cmd_par.setText(_translate("cebsMengForm", "0"))
        self.label_meng_cmd_par.setText(_translate("cebsMengForm", "命令返回参数"))

