# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cebsCalibform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cebsCalibForm(object):
    def setupUi(self, cebsCalibForm):
        cebsCalibForm.setObjectName("cebsCalibForm")
        cebsCalibForm.resize(1194, 443)
        self.groupBox_calib_set = QtWidgets.QGroupBox(cebsCalibForm)
        self.groupBox_calib_set.setGeometry(QtCore.QRect(30, 20, 341, 241))
        self.groupBox_calib_set.setObjectName("groupBox_calib_set")
        self.groupBox_calib_move_scale = QtWidgets.QGroupBox(self.groupBox_calib_set)
        self.groupBox_calib_move_scale.setGeometry(QtCore.QRect(10, 70, 311, 51))
        self.groupBox_calib_move_scale.setObjectName("groupBox_calib_move_scale")
        self.radioButton_calib_5cm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_5cm.setGeometry(QtCore.QRect(220, 20, 41, 21))
        self.radioButton_calib_5cm.setObjectName("radioButton_calib_5cm")
        self.radioButton_calib_05mm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_05mm.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.radioButton_calib_05mm.setChecked(True)
        self.radioButton_calib_05mm.setObjectName("radioButton_calib_05mm")
        self.radioButton_calib_1cm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_1cm.setGeometry(QtCore.QRect(170, 20, 41, 21))
        self.radioButton_calib_1cm.setObjectName("radioButton_calib_1cm")
        self.radioButton_calib_1mm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_1mm.setGeometry(QtCore.QRect(70, 20, 41, 21))
        self.radioButton_calib_1mm.setChecked(False)
        self.radioButton_calib_1mm.setObjectName("radioButton_calib_1mm")
        self.radioButton_calib_5mm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_5mm.setGeometry(QtCore.QRect(120, 20, 41, 21))
        self.radioButton_calib_5mm.setObjectName("radioButton_calib_5mm")
        self.groupBox_calib_move_dir = QtWidgets.QGroupBox(self.groupBox_calib_set)
        self.groupBox_calib_move_dir.setGeometry(QtCore.QRect(10, 130, 311, 51))
        self.groupBox_calib_move_dir.setObjectName("groupBox_calib_move_dir")
        self.radioButton_calib_y_plus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_y_plus.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.radioButton_calib_y_plus.setChecked(True)
        self.radioButton_calib_y_plus.setObjectName("radioButton_calib_y_plus")
        self.radioButton_calib_x_plus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_x_plus.setGeometry(QtCore.QRect(210, 20, 61, 21))
        self.radioButton_calib_x_plus.setObjectName("radioButton_calib_x_plus")
        self.radioButton_calib_y_minus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_y_minus.setGeometry(QtCore.QRect(80, 20, 61, 21))
        self.radioButton_calib_y_minus.setChecked(False)
        self.radioButton_calib_y_minus.setObjectName("radioButton_calib_y_minus")
        self.radioButton_calib_x_minus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_x_minus.setGeometry(QtCore.QRect(140, 20, 61, 21))
        self.radioButton_calib_x_minus.setObjectName("radioButton_calib_x_minus")
        self.pushButton_calib_move = QtWidgets.QPushButton(self.groupBox_calib_set)
        self.pushButton_calib_move.setGeometry(QtCore.QRect(10, 20, 321, 41))
        self.pushButton_calib_move.setObjectName("pushButton_calib_move")
        self.pushButton_calib_left_up = QtWidgets.QPushButton(self.groupBox_calib_set)
        self.pushButton_calib_left_up.setGeometry(QtCore.QRect(10, 190, 141, 41))
        self.pushButton_calib_left_up.setObjectName("pushButton_calib_left_up")
        self.pushButton_calib_right_bottom = QtWidgets.QPushButton(self.groupBox_calib_set)
        self.pushButton_calib_right_bottom.setGeometry(QtCore.QRect(180, 190, 141, 41))
        self.pushButton_calib_right_bottom.setObjectName("pushButton_calib_right_bottom")
        self.textEdit_calib_runProgress = QtWidgets.QTextEdit(cebsCalibForm)
        self.textEdit_calib_runProgress.setGeometry(QtCore.QRect(400, 30, 751, 391))
        self.textEdit_calib_runProgress.setMouseTracking(True)
        self.textEdit_calib_runProgress.setTabletTracking(True)
        self.textEdit_calib_runProgress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_calib_runProgress.setAutoFillBackground(True)
        self.textEdit_calib_runProgress.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_calib_runProgress.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_calib_runProgress.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_calib_runProgress.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_calib_runProgress.setTabChangesFocus(True)
        self.textEdit_calib_runProgress.setObjectName("textEdit_calib_runProgress")
        self.label_calib_runProgress = QtWidgets.QLabel(cebsCalibForm)
        self.label_calib_runProgress.setGeometry(QtCore.QRect(400, 10, 261, 16))
        self.label_calib_runProgress.setObjectName("label_calib_runProgress")
        self.pushButton_calib_pilot = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_pilot.setGeometry(QtCore.QRect(30, 280, 161, 61))
        self.pushButton_calib_pilot.setObjectName("pushButton_calib_pilot")
        self.pushButton_calib_comp = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_comp.setGeometry(QtCore.QRect(30, 360, 341, 61))
        self.pushButton_calib_comp.setObjectName("pushButton_calib_comp")
        self.pushButton_calib_pilot_2 = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_pilot_2.setGeometry(QtCore.QRect(210, 280, 161, 61))
        self.pushButton_calib_pilot_2.setObjectName("pushButton_calib_pilot_2")

        self.retranslateUi(cebsCalibForm)
        self.pushButton_calib_comp.clicked.connect(cebsCalibForm.slot_calib_close)
        self.pushButton_calib_move.clicked.connect(cebsCalibForm.slot_calib_move)
        self.pushButton_calib_left_up.clicked.connect(cebsCalibForm.slot_calib_left_up)
        self.pushButton_calib_right_bottom.clicked.connect(cebsCalibForm.slot_calib_right_bottom)
        self.pushButton_calib_pilot.clicked.connect(cebsCalibForm.slot_calib_pilot)
        self.pushButton_calib_pilot_2.clicked.connect(cebsCalibForm.slot_calib_pilot_stop)
        QtCore.QMetaObject.connectSlotsByName(cebsCalibForm)

    def retranslateUi(self, cebsCalibForm):
        _translate = QtCore.QCoreApplication.translate
        cebsCalibForm.setWindowTitle(_translate("cebsCalibForm", "CALIBRATION"))
        self.groupBox_calib_set.setTitle(_translate("cebsCalibForm", "校准设定"))
        self.groupBox_calib_move_scale.setTitle(_translate("cebsCalibForm", "运动刻度"))
        self.radioButton_calib_5cm.setText(_translate("cebsCalibForm", "5cm"))
        self.radioButton_calib_05mm.setText(_translate("cebsCalibForm", "0.5mm"))
        self.radioButton_calib_1cm.setText(_translate("cebsCalibForm", "1cm"))
        self.radioButton_calib_1mm.setText(_translate("cebsCalibForm", "1mm"))
        self.radioButton_calib_5mm.setText(_translate("cebsCalibForm", "5mm"))
        self.groupBox_calib_move_dir.setTitle(_translate("cebsCalibForm", "运动方向"))
        self.radioButton_calib_y_plus.setText(_translate("cebsCalibForm", "上(Y+)"))
        self.radioButton_calib_x_plus.setText(_translate("cebsCalibForm", "右(X+)"))
        self.radioButton_calib_y_minus.setText(_translate("cebsCalibForm", "下(Y-)"))
        self.radioButton_calib_x_minus.setText(_translate("cebsCalibForm", "左(X-)"))
        self.pushButton_calib_move.setText(_translate("cebsCalibForm", "移动"))
        self.pushButton_calib_left_up.setText(_translate("cebsCalibForm", "设定左上"))
        self.pushButton_calib_right_bottom.setText(_translate("cebsCalibForm", "设定右下"))
        self.textEdit_calib_runProgress.setHtml(_translate("cebsCalibForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt;&gt; 2018/5/2 15:30:99 校准开始</p></body></html>"))
        self.label_calib_runProgress.setText(_translate("cebsCalibForm", "校准进展"))
        self.pushButton_calib_pilot.setText(_translate("cebsCalibForm", "校准巡游"))
        self.pushButton_calib_comp.setText(_translate("cebsCalibForm", "校准完成"))
        self.pushButton_calib_pilot_2.setText(_translate("cebsCalibForm", "巡游停止"))

