# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cebsCalibform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cebsCalibForm(object):
    def setupUi(self, cebsCalibForm):
        cebsCalibForm.setObjectName("cebsCalibForm")
        cebsCalibForm.resize(1194, 801)
        self.groupBox_calib_set = QtWidgets.QGroupBox(cebsCalibForm)
        self.groupBox_calib_set.setGeometry(QtCore.QRect(30, 10, 881, 241))
        self.groupBox_calib_set.setObjectName("groupBox_calib_set")
        self.groupBox_calib_move_scale = QtWidgets.QGroupBox(self.groupBox_calib_set)
        self.groupBox_calib_move_scale.setGeometry(QtCore.QRect(20, 80, 841, 81))
        self.groupBox_calib_move_scale.setObjectName("groupBox_calib_move_scale")
        self.radioButton_calib_5cm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_5cm.setGeometry(QtCore.QRect(650, 20, 51, 21))
        self.radioButton_calib_5cm.setObjectName("radioButton_calib_5cm")
        self.radioButton_calib_2mm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_2mm.setGeometry(QtCore.QRect(360, 20, 61, 21))
        self.radioButton_calib_2mm.setChecked(False)
        self.radioButton_calib_2mm.setObjectName("radioButton_calib_2mm")
        self.radioButton_calib_2cm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_2cm.setGeometry(QtCore.QRect(580, 20, 51, 21))
        self.radioButton_calib_2cm.setObjectName("radioButton_calib_2cm")
        self.radioButton_calib_5mm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_5mm.setGeometry(QtCore.QRect(440, 20, 51, 21))
        self.radioButton_calib_5mm.setChecked(False)
        self.radioButton_calib_5mm.setObjectName("radioButton_calib_5mm")
        self.radioButton_calib_1cm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_1cm.setGeometry(QtCore.QRect(510, 20, 51, 21))
        self.radioButton_calib_1cm.setObjectName("radioButton_calib_1cm")
        self.radioButton_calib_10um = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_10um.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.radioButton_calib_10um.setChecked(False)
        self.radioButton_calib_10um.setObjectName("radioButton_calib_10um")
        self.radioButton_calib_100um = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_100um.setGeometry(QtCore.QRect(90, 20, 61, 21))
        self.radioButton_calib_100um.setChecked(False)
        self.radioButton_calib_100um.setObjectName("radioButton_calib_100um")
        self.radioButton_calib_200um = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_200um.setGeometry(QtCore.QRect(160, 20, 61, 21))
        self.radioButton_calib_200um.setChecked(False)
        self.radioButton_calib_200um.setObjectName("radioButton_calib_200um")
        self.radioButton_calib_500um = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_500um.setGeometry(QtCore.QRect(230, 20, 61, 21))
        self.radioButton_calib_500um.setChecked(False)
        self.radioButton_calib_500um.setObjectName("radioButton_calib_500um")
        self.radioButton_calib_1mm = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_1mm.setGeometry(QtCore.QRect(300, 20, 61, 21))
        self.radioButton_calib_1mm.setChecked(True)
        self.radioButton_calib_1mm.setObjectName("radioButton_calib_1mm")
        self.radioButton_calib_hole96_l = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole96_l.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.radioButton_calib_hole96_l.setObjectName("radioButton_calib_hole96_l")
        self.radioButton_calib_hole96_s = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole96_s.setGeometry(QtCore.QRect(90, 50, 71, 21))
        self.radioButton_calib_hole96_s.setObjectName("radioButton_calib_hole96_s")
        self.radioButton_calib_hole48_l = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole48_l.setGeometry(QtCore.QRect(160, 50, 71, 21))
        self.radioButton_calib_hole48_l.setObjectName("radioButton_calib_hole48_l")
        self.radioButton_calib_hole48_s = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole48_s.setGeometry(QtCore.QRect(230, 50, 71, 21))
        self.radioButton_calib_hole48_s.setObjectName("radioButton_calib_hole48_s")
        self.radioButton_calib_hole24_s = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole24_s.setGeometry(QtCore.QRect(370, 50, 71, 21))
        self.radioButton_calib_hole24_s.setObjectName("radioButton_calib_hole24_s")
        self.radioButton_calib_hole24_l = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole24_l.setGeometry(QtCore.QRect(300, 50, 71, 21))
        self.radioButton_calib_hole24_l.setObjectName("radioButton_calib_hole24_l")
        self.radioButton_calib_hole12_s = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole12_s.setGeometry(QtCore.QRect(510, 50, 71, 21))
        self.radioButton_calib_hole12_s.setObjectName("radioButton_calib_hole12_s")
        self.radioButton_calib_hole12_l = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole12_l.setGeometry(QtCore.QRect(440, 50, 71, 21))
        self.radioButton_calib_hole12_l.setObjectName("radioButton_calib_hole12_l")
        self.radioButton_calib_hole6_s = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole6_s.setGeometry(QtCore.QRect(650, 50, 71, 21))
        self.radioButton_calib_hole6_s.setObjectName("radioButton_calib_hole6_s")
        self.radioButton_calib_hole6_l = QtWidgets.QRadioButton(self.groupBox_calib_move_scale)
        self.radioButton_calib_hole6_l.setGeometry(QtCore.QRect(580, 50, 71, 21))
        self.radioButton_calib_hole6_l.setObjectName("radioButton_calib_hole6_l")
        self.groupBox_calib_move_dir = QtWidgets.QGroupBox(self.groupBox_calib_set)
        self.groupBox_calib_move_dir.setGeometry(QtCore.QRect(10, 170, 351, 61))
        self.groupBox_calib_move_dir.setObjectName("groupBox_calib_move_dir")
        self.radioButton_calib_y_plus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_y_plus.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.radioButton_calib_y_plus.setChecked(True)
        self.radioButton_calib_y_plus.setObjectName("radioButton_calib_y_plus")
        self.radioButton_calib_x_plus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_x_plus.setGeometry(QtCore.QRect(280, 20, 61, 21))
        self.radioButton_calib_x_plus.setObjectName("radioButton_calib_x_plus")
        self.radioButton_calib_y_minus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_y_minus.setGeometry(QtCore.QRect(100, 20, 61, 21))
        self.radioButton_calib_y_minus.setChecked(False)
        self.radioButton_calib_y_minus.setObjectName("radioButton_calib_y_minus")
        self.radioButton_calib_x_minus = QtWidgets.QRadioButton(self.groupBox_calib_move_dir)
        self.radioButton_calib_x_minus.setGeometry(QtCore.QRect(190, 20, 61, 21))
        self.radioButton_calib_x_minus.setObjectName("radioButton_calib_x_minus")
        self.pushButton_calib_left_down = QtWidgets.QPushButton(self.groupBox_calib_set)
        self.pushButton_calib_left_down.setGeometry(QtCore.QRect(400, 170, 81, 31))
        self.pushButton_calib_left_down.setObjectName("pushButton_calib_left_down")
        self.pushButton_calib_right_up = QtWidgets.QPushButton(self.groupBox_calib_set)
        self.pushButton_calib_right_up.setGeometry(QtCore.QRect(400, 200, 81, 31))
        self.pushButton_calib_right_up.setObjectName("pushButton_calib_right_up")
        self.groupBox_calib_bts = QtWidgets.QGroupBox(self.groupBox_calib_set)
        self.groupBox_calib_bts.setGeometry(QtCore.QRect(20, 20, 841, 51))
        self.groupBox_calib_bts.setObjectName("groupBox_calib_bts")
        self.radioButton_calib_bts_96 = QtWidgets.QRadioButton(self.groupBox_calib_bts)
        self.radioButton_calib_bts_96.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.radioButton_calib_bts_96.setChecked(True)
        self.radioButton_calib_bts_96.setObjectName("radioButton_calib_bts_96")
        self.radioButton_calib_bts_48 = QtWidgets.QRadioButton(self.groupBox_calib_bts)
        self.radioButton_calib_bts_48.setGeometry(QtCore.QRect(100, 20, 61, 21))
        self.radioButton_calib_bts_48.setChecked(False)
        self.radioButton_calib_bts_48.setObjectName("radioButton_calib_bts_48")
        self.radioButton_calib_bts_24 = QtWidgets.QRadioButton(self.groupBox_calib_bts)
        self.radioButton_calib_bts_24.setGeometry(QtCore.QRect(200, 20, 61, 21))
        self.radioButton_calib_bts_24.setChecked(False)
        self.radioButton_calib_bts_24.setObjectName("radioButton_calib_bts_24")
        self.radioButton_calib_bts_12 = QtWidgets.QRadioButton(self.groupBox_calib_bts)
        self.radioButton_calib_bts_12.setGeometry(QtCore.QRect(300, 20, 61, 21))
        self.radioButton_calib_bts_12.setChecked(False)
        self.radioButton_calib_bts_12.setObjectName("radioButton_calib_bts_12")
        self.radioButton_calib_bts_6 = QtWidgets.QRadioButton(self.groupBox_calib_bts)
        self.radioButton_calib_bts_6.setGeometry(QtCore.QRect(400, 20, 61, 21))
        self.radioButton_calib_bts_6.setChecked(False)
        self.radioButton_calib_bts_6.setObjectName("radioButton_calib_bts_6")
        self.pushButton_calib_move = QtWidgets.QPushButton(self.groupBox_calib_set)
        self.pushButton_calib_move.setGeometry(QtCore.QRect(540, 170, 321, 61))
        self.pushButton_calib_move.setObjectName("pushButton_calib_move")
        self.textEdit_calib_runProgress = QtWidgets.QTextEdit(cebsCalibForm)
        self.textEdit_calib_runProgress.setGeometry(QtCore.QRect(420, 350, 731, 421))
        self.textEdit_calib_runProgress.setMouseTracking(True)
        self.textEdit_calib_runProgress.setTabletTracking(True)
        self.textEdit_calib_runProgress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_calib_runProgress.setAutoFillBackground(True)
        self.textEdit_calib_runProgress.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_calib_runProgress.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_calib_runProgress.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_calib_runProgress.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_calib_runProgress.setTabChangesFocus(True)
        self.textEdit_calib_runProgress.setObjectName("textEdit_calib_runProgress")
        self.label_calib_runProgress = QtWidgets.QLabel(cebsCalibForm)
        self.label_calib_runProgress.setGeometry(QtCore.QRect(420, 330, 81, 16))
        self.label_calib_runProgress.setObjectName("label_calib_runProgress")
        self.pushButton_calib_comp = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_comp.setGeometry(QtCore.QRect(30, 420, 371, 71))
        self.pushButton_calib_comp.setObjectName("pushButton_calib_comp")
        self.pushButton_calib_fm_1cm = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_fm_1cm.setGeometry(QtCore.QRect(140, 590, 131, 111))
        self.pushButton_calib_fm_1cm.setObjectName("pushButton_calib_fm_1cm")
        self.pushButton_calib_fm_up = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_fm_up.setGeometry(QtCore.QRect(140, 550, 131, 31))
        self.pushButton_calib_fm_up.setObjectName("pushButton_calib_fm_up")
        self.pushButton_calib_fm_down = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_fm_down.setGeometry(QtCore.QRect(140, 710, 131, 31))
        self.pushButton_calib_fm_down.setObjectName("pushButton_calib_fm_down")
        self.pushButton_calib_fm_right = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_fm_right.setGeometry(QtCore.QRect(280, 590, 31, 111))
        self.pushButton_calib_fm_right.setObjectName("pushButton_calib_fm_right")
        self.pushButton_calib_fm_left = QtWidgets.QPushButton(cebsCalibForm)
        self.pushButton_calib_fm_left.setGeometry(QtCore.QRect(100, 590, 31, 111))
        self.pushButton_calib_fm_left.setObjectName("pushButton_calib_fm_left")
        self.textEdit_calib_runProgress_2 = QtWidgets.QTextEdit(cebsCalibForm)
        self.textEdit_calib_runProgress_2.setGeometry(QtCore.QRect(420, 270, 731, 31))
        self.textEdit_calib_runProgress_2.setMouseTracking(True)
        self.textEdit_calib_runProgress_2.setTabletTracking(True)
        self.textEdit_calib_runProgress_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_calib_runProgress_2.setAutoFillBackground(True)
        self.textEdit_calib_runProgress_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_calib_runProgress_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_calib_runProgress_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_calib_runProgress_2.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_calib_runProgress_2.setTabChangesFocus(True)
        self.textEdit_calib_runProgress_2.setObjectName("textEdit_calib_runProgress_2")
        self.groupBox_calib_pilot = QtWidgets.QGroupBox(cebsCalibForm)
        self.groupBox_calib_pilot.setGeometry(QtCore.QRect(30, 270, 371, 131))
        self.groupBox_calib_pilot.setObjectName("groupBox_calib_pilot")
        self.pushButton_calib_pilot_start = QtWidgets.QPushButton(self.groupBox_calib_pilot)
        self.pushButton_calib_pilot_start.setGeometry(QtCore.QRect(10, 80, 81, 41))
        self.pushButton_calib_pilot_start.setObjectName("pushButton_calib_pilot_start")
        self.pushButton_calib_pilot_stop = QtWidgets.QPushButton(self.groupBox_calib_pilot)
        self.pushButton_calib_pilot_stop.setGeometry(QtCore.QRect(100, 80, 81, 41))
        self.pushButton_calib_pilot_stop.setObjectName("pushButton_calib_pilot_stop")
        self.pushButton_calib_pilot_move_0 = QtWidgets.QPushButton(self.groupBox_calib_pilot)
        self.pushButton_calib_pilot_move_0.setGeometry(QtCore.QRect(10, 30, 81, 41))
        self.pushButton_calib_pilot_move_0.setObjectName("pushButton_calib_pilot_move_0")
        self.pushButton_calib_pilot_move_n = QtWidgets.QPushButton(self.groupBox_calib_pilot)
        self.pushButton_calib_pilot_move_n.setGeometry(QtCore.QRect(100, 30, 81, 41))
        self.pushButton_calib_pilot_move_n.setObjectName("pushButton_calib_pilot_move_n")
        self.lineEdit_pilot_move_n = QtWidgets.QLineEdit(self.groupBox_calib_pilot)
        self.lineEdit_pilot_move_n.setGeometry(QtCore.QRect(190, 40, 51, 20))
        self.lineEdit_pilot_move_n.setObjectName("lineEdit_pilot_move_n")
        self.pushButton_calib_pilot_camera_enable = QtWidgets.QPushButton(self.groupBox_calib_pilot)
        self.pushButton_calib_pilot_camera_enable.setGeometry(QtCore.QRect(280, 30, 81, 41))
        self.pushButton_calib_pilot_camera_enable.setObjectName("pushButton_calib_pilot_camera_enable")
        self.graphicsView_pilot_display = QtWidgets.QGraphicsView(cebsCalibForm)
        self.graphicsView_pilot_display.setGeometry(QtCore.QRect(420, 300, 731, 21))
        self.graphicsView_pilot_display.setObjectName("graphicsView_pilot_display")

        self.retranslateUi(cebsCalibForm)
        self.pushButton_calib_comp.clicked.connect(cebsCalibForm.slot_calib_close)
        self.pushButton_calib_move.clicked.connect(cebsCalibForm.slot_calib_move)
        self.pushButton_calib_left_down.clicked.connect(cebsCalibForm.slot_calib_left_down)
        self.pushButton_calib_right_up.clicked.connect(cebsCalibForm.slot_calib_right_up)
        self.pushButton_calib_pilot_start.clicked.connect(cebsCalibForm.slot_calib_pilot_start)
        self.pushButton_calib_pilot_stop.clicked.connect(cebsCalibForm.slot_calib_pilot_stop)
        self.pushButton_calib_fm_left.clicked.connect(cebsCalibForm.slot_calib_fm_left)
        self.pushButton_calib_fm_down.clicked.connect(cebsCalibForm.slot_calib_fm_down)
        self.pushButton_calib_fm_right.clicked.connect(cebsCalibForm.slot_calib_fm_right)
        self.pushButton_calib_fm_up.clicked.connect(cebsCalibForm.slot_calib_fm_up)
        self.pushButton_calib_pilot_move_0.clicked.connect(cebsCalibForm.slot_calib_pilot_move_0)
        self.pushButton_calib_pilot_move_n.clicked.connect(cebsCalibForm.slot_calib_pilot_move_n)
        self.pushButton_calib_pilot_camera_enable.clicked.connect(cebsCalibForm.slot_calib_pilot_camera_enable)
        QtCore.QMetaObject.connectSlotsByName(cebsCalibForm)

    def retranslateUi(self, cebsCalibForm):
        _translate = QtCore.QCoreApplication.translate
        cebsCalibForm.setWindowTitle(_translate("cebsCalibForm", "CALIBRATION"))
        self.groupBox_calib_set.setTitle(_translate("cebsCalibForm", "校准设定"))
        self.groupBox_calib_move_scale.setTitle(_translate("cebsCalibForm", "运动刻度"))
        self.radioButton_calib_5cm.setText(_translate("cebsCalibForm", "5cm"))
        self.radioButton_calib_2mm.setText(_translate("cebsCalibForm", "2mm"))
        self.radioButton_calib_2cm.setText(_translate("cebsCalibForm", "2cm"))
        self.radioButton_calib_5mm.setText(_translate("cebsCalibForm", "5mm"))
        self.radioButton_calib_1cm.setText(_translate("cebsCalibForm", "1cm"))
        self.radioButton_calib_10um.setText(_translate("cebsCalibForm", "10um"))
        self.radioButton_calib_100um.setText(_translate("cebsCalibForm", "100um"))
        self.radioButton_calib_200um.setText(_translate("cebsCalibForm", "200um"))
        self.radioButton_calib_500um.setText(_translate("cebsCalibForm", "500um"))
        self.radioButton_calib_1mm.setText(_translate("cebsCalibForm", "1mm"))
        self.radioButton_calib_hole96_l.setText(_translate("cebsCalibForm", "96孔长边"))
        self.radioButton_calib_hole96_s.setText(_translate("cebsCalibForm", "96孔短边"))
        self.radioButton_calib_hole48_l.setText(_translate("cebsCalibForm", "48孔长边"))
        self.radioButton_calib_hole48_s.setText(_translate("cebsCalibForm", "48孔短边"))
        self.radioButton_calib_hole24_s.setText(_translate("cebsCalibForm", "24孔短边"))
        self.radioButton_calib_hole24_l.setText(_translate("cebsCalibForm", "24孔长边"))
        self.radioButton_calib_hole12_s.setText(_translate("cebsCalibForm", "12孔短边"))
        self.radioButton_calib_hole12_l.setText(_translate("cebsCalibForm", "12孔长边"))
        self.radioButton_calib_hole6_s.setText(_translate("cebsCalibForm", "6孔短边"))
        self.radioButton_calib_hole6_l.setText(_translate("cebsCalibForm", "6孔长边"))
        self.groupBox_calib_move_dir.setTitle(_translate("cebsCalibForm", "运动方向"))
        self.radioButton_calib_y_plus.setText(_translate("cebsCalibForm", "上(Y+)"))
        self.radioButton_calib_x_plus.setText(_translate("cebsCalibForm", "右(X+)"))
        self.radioButton_calib_y_minus.setText(_translate("cebsCalibForm", "下(Y-)"))
        self.radioButton_calib_x_minus.setText(_translate("cebsCalibForm", "左(X-)"))
        self.pushButton_calib_left_down.setText(_translate("cebsCalibForm", "设定左下"))
        self.pushButton_calib_right_up.setText(_translate("cebsCalibForm", "设定右上"))
        self.groupBox_calib_bts.setTitle(_translate("cebsCalibForm", "板型选择"))
        self.radioButton_calib_bts_96.setText(_translate("cebsCalibForm", "96孔板"))
        self.radioButton_calib_bts_48.setText(_translate("cebsCalibForm", "48孔板"))
        self.radioButton_calib_bts_24.setText(_translate("cebsCalibForm", "24孔板"))
        self.radioButton_calib_bts_12.setText(_translate("cebsCalibForm", "12孔板"))
        self.radioButton_calib_bts_6.setText(_translate("cebsCalibForm", "6孔板"))
        self.pushButton_calib_move.setText(_translate("cebsCalibForm", "移动"))
        self.textEdit_calib_runProgress.setHtml(_translate("cebsCalibForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&gt;&gt; 2018/5/2 15:30:99 校准开始</p></body></html>"))
        self.label_calib_runProgress.setText(_translate("cebsCalibForm", "校准进展"))
        self.pushButton_calib_comp.setText(_translate("cebsCalibForm", "校准完成"))
        self.pushButton_calib_fm_1cm.setText(_translate("cebsCalibForm", "强制移动（1cm)"))
        self.pushButton_calib_fm_up.setText(_translate("cebsCalibForm", "上"))
        self.pushButton_calib_fm_down.setText(_translate("cebsCalibForm", "下"))
        self.pushButton_calib_fm_right.setText(_translate("cebsCalibForm", "右"))
        self.pushButton_calib_fm_left.setText(_translate("cebsCalibForm", "左"))
        self.textEdit_calib_runProgress_2.setHtml(_translate("cebsCalibForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">实时图像</p></body></html>"))
        self.groupBox_calib_pilot.setTitle(_translate("cebsCalibForm", "运动设置"))
        self.pushButton_calib_pilot_start.setText(_translate("cebsCalibForm", "校准巡游"))
        self.pushButton_calib_pilot_stop.setText(_translate("cebsCalibForm", "巡游停止"))
        self.pushButton_calib_pilot_move_0.setText(_translate("cebsCalibForm", "移动到起点"))
        self.pushButton_calib_pilot_move_n.setText(_translate("cebsCalibForm", "移动到#号孔"))
        self.lineEdit_pilot_move_n.setText(_translate("cebsCalibForm", "1"))
        self.pushButton_calib_pilot_camera_enable.setText(_translate("cebsCalibForm", "摄像头激活"))

