# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cebsGparform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cebsGparForm(object):
    def setupUi(self, cebsGparForm):
        cebsGparForm.setObjectName("cebsGparForm")
        cebsGparForm.resize(1194, 633)
        self.groupBox_gpar = QtWidgets.QGroupBox(cebsGparForm)
        self.groupBox_gpar.setGeometry(QtCore.QRect(20, 30, 331, 91))
        self.groupBox_gpar.setObjectName("groupBox_gpar")
        self.checkBox_gpar_autoIdf = QtWidgets.QCheckBox(self.groupBox_gpar)
        self.checkBox_gpar_autoIdf.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.checkBox_gpar_autoIdf.setChecked(True)
        self.checkBox_gpar_autoIdf.setObjectName("checkBox_gpar_autoIdf")
        self.lineEdit_gpar_picTti = QtWidgets.QLineEdit(self.groupBox_gpar)
        self.lineEdit_gpar_picTti.setGeometry(QtCore.QRect(90, 60, 51, 20))
        self.lineEdit_gpar_picTti.setObjectName("lineEdit_gpar_picTti")
        self.label_gpar_picTti_title = QtWidgets.QLabel(self.groupBox_gpar)
        self.label_gpar_picTti_title.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_gpar_picTti_title.setObjectName("label_gpar_picTti_title")
        self.label_gpar_picTti_min = QtWidgets.QLabel(self.groupBox_gpar)
        self.label_gpar_picTti_min.setGeometry(QtCore.QRect(150, 60, 31, 16))
        self.label_gpar_picTti_min.setObjectName("label_gpar_picTti_min")
        self.checkBox_gpar_autoPic = QtWidgets.QCheckBox(self.groupBox_gpar)
        self.checkBox_gpar_autoPic.setGeometry(QtCore.QRect(130, 30, 111, 16))
        self.checkBox_gpar_autoPic.setChecked(True)
        self.checkBox_gpar_autoPic.setObjectName("checkBox_gpar_autoPic")
        self.checkBox_gpar_picFixPos = QtWidgets.QCheckBox(self.groupBox_gpar)
        self.checkBox_gpar_picFixPos.setGeometry(QtCore.QRect(240, 30, 71, 16))
        self.checkBox_gpar_picFixPos.setChecked(False)
        self.checkBox_gpar_picFixPos.setObjectName("checkBox_gpar_picFixPos")
        self.groupBox_gpar_2 = QtWidgets.QGroupBox(cebsGparForm)
        self.groupBox_gpar_2.setGeometry(QtCore.QRect(20, 150, 331, 191))
        self.groupBox_gpar_2.setObjectName("groupBox_gpar_2")
        self.lineEdit_gpar_vision_small_low_limit = QtWidgets.QLineEdit(self.groupBox_gpar_2)
        self.lineEdit_gpar_vision_small_low_limit.setGeometry(QtCore.QRect(130, 30, 51, 20))
        self.lineEdit_gpar_vision_small_low_limit.setObjectName("lineEdit_gpar_vision_small_low_limit")
        self.label_gpar_picTti_min_2 = QtWidgets.QLabel(self.groupBox_gpar_2)
        self.label_gpar_picTti_min_2.setGeometry(QtCore.QRect(10, 30, 111, 21))
        self.label_gpar_picTti_min_2.setObjectName("label_gpar_picTti_min_2")
        self.lineEdit_gpar_vision_small_mid_limit = QtWidgets.QLineEdit(self.groupBox_gpar_2)
        self.lineEdit_gpar_vision_small_mid_limit.setGeometry(QtCore.QRect(130, 60, 51, 20))
        self.lineEdit_gpar_vision_small_mid_limit.setObjectName("lineEdit_gpar_vision_small_mid_limit")
        self.label_gpar_picTti_min_3 = QtWidgets.QLabel(self.groupBox_gpar_2)
        self.label_gpar_picTti_min_3.setGeometry(QtCore.QRect(10, 60, 111, 21))
        self.label_gpar_picTti_min_3.setObjectName("label_gpar_picTti_min_3")
        self.lineEdit_gpar_vision_mid_big_limit = QtWidgets.QLineEdit(self.groupBox_gpar_2)
        self.lineEdit_gpar_vision_mid_big_limit.setGeometry(QtCore.QRect(130, 90, 51, 20))
        self.lineEdit_gpar_vision_mid_big_limit.setObjectName("lineEdit_gpar_vision_mid_big_limit")
        self.label_gpar_picTti_min_4 = QtWidgets.QLabel(self.groupBox_gpar_2)
        self.label_gpar_picTti_min_4.setGeometry(QtCore.QRect(10, 90, 111, 21))
        self.label_gpar_picTti_min_4.setObjectName("label_gpar_picTti_min_4")
        self.lineEdit_gpar_vision_big_upper_limit = QtWidgets.QLineEdit(self.groupBox_gpar_2)
        self.lineEdit_gpar_vision_big_upper_limit.setGeometry(QtCore.QRect(130, 120, 51, 20))
        self.lineEdit_gpar_vision_big_upper_limit.setObjectName("lineEdit_gpar_vision_big_upper_limit")
        self.label_gpar_picTti_min_5 = QtWidgets.QLabel(self.groupBox_gpar_2)
        self.label_gpar_picTti_min_5.setGeometry(QtCore.QRect(10, 120, 111, 21))
        self.label_gpar_picTti_min_5.setObjectName("label_gpar_picTti_min_5")
        self.checkBox_gpar_vision_res_addup = QtWidgets.QCheckBox(self.groupBox_gpar_2)
        self.checkBox_gpar_vision_res_addup.setGeometry(QtCore.QRect(10, 160, 181, 16))
        self.checkBox_gpar_vision_res_addup.setChecked(True)
        self.checkBox_gpar_vision_res_addup.setObjectName("checkBox_gpar_vision_res_addup")
        self.pushButton_ctrl_compl = QtWidgets.QPushButton(cebsGparForm)
        self.pushButton_ctrl_compl.setGeometry(QtCore.QRect(670, 270, 261, 71))
        self.pushButton_ctrl_compl.setObjectName("pushButton_ctrl_compl")
        self.groupBox_eng = QtWidgets.QGroupBox(cebsGparForm)
        self.groupBox_eng.setGeometry(QtCore.QRect(370, 40, 561, 81))
        self.groupBox_eng.setObjectName("groupBox_eng")
        self.textEdit_eng_input = QtWidgets.QTextEdit(self.groupBox_eng)
        self.textEdit_eng_input.setGeometry(QtCore.QRect(20, 30, 341, 41))
        self.textEdit_eng_input.setMouseTracking(True)
        self.textEdit_eng_input.setTabletTracking(True)
        self.textEdit_eng_input.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_eng_input.setAutoFillBackground(True)
        self.textEdit_eng_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_eng_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_eng_input.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_eng_input.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.textEdit_eng_input.setTabChangesFocus(True)
        self.textEdit_eng_input.setObjectName("textEdit_eng_input")
        self.pushButton_eng_send = QtWidgets.QPushButton(self.groupBox_eng)
        self.pushButton_eng_send.setGeometry(QtCore.QRect(390, 30, 71, 41))
        self.pushButton_eng_send.setObjectName("pushButton_eng_send")
        self.pushButton_eng_clear = QtWidgets.QPushButton(self.groupBox_eng)
        self.pushButton_eng_clear.setGeometry(QtCore.QRect(470, 30, 71, 41))
        self.pushButton_eng_clear.setObjectName("pushButton_eng_clear")
        self.pushButton_ctrl_giveup = QtWidgets.QPushButton(cebsGparForm)
        self.pushButton_ctrl_giveup.setGeometry(QtCore.QRect(370, 270, 261, 71))
        self.pushButton_ctrl_giveup.setObjectName("pushButton_ctrl_giveup")

        self.retranslateUi(cebsGparForm)
        self.pushButton_ctrl_compl.clicked.connect(cebsGparForm.slot_gpar_compl)
        self.pushButton_ctrl_giveup.clicked.connect(cebsGparForm.slot_gpar_giveup)
        QtCore.QMetaObject.connectSlotsByName(cebsGparForm)

    def retranslateUi(self, cebsGparForm):
        _translate = QtCore.QCoreApplication.translate
        cebsGparForm.setWindowTitle(_translate("cebsGparForm", "GLOBAL PARAMETER"))
        self.groupBox_gpar.setTitle(_translate("cebsGparForm", "全局参数设置"))
        self.checkBox_gpar_autoIdf.setText(_translate("cebsGparForm", "拍照后自动识别"))
        self.lineEdit_gpar_picTti.setText(_translate("cebsGparForm", "60"))
        self.label_gpar_picTti_title.setText(_translate("cebsGparForm", "定时拍照间隔"))
        self.label_gpar_picTti_min.setText(_translate("cebsGparForm", "分钟"))
        self.checkBox_gpar_autoPic.setText(_translate("cebsGparForm", "定时自动拍照"))
        self.checkBox_gpar_picFixPos.setText(_translate("cebsGparForm", "定点拍照"))
        self.groupBox_gpar_2.setTitle(_translate("cebsGparForm", "图像识别参数设置"))
        self.lineEdit_gpar_vision_small_low_limit.setText(_translate("cebsGparForm", "200"))
        self.label_gpar_picTti_min_2.setText(_translate("cebsGparForm", "小尺寸门限"))
        self.lineEdit_gpar_vision_small_mid_limit.setText(_translate("cebsGparForm", "500"))
        self.label_gpar_picTti_min_3.setText(_translate("cebsGparForm", "小-中尺寸门限"))
        self.lineEdit_gpar_vision_mid_big_limit.setText(_translate("cebsGparForm", "2000"))
        self.label_gpar_picTti_min_4.setText(_translate("cebsGparForm", "中-大尺寸门限"))
        self.lineEdit_gpar_vision_big_upper_limit.setText(_translate("cebsGparForm", "5000"))
        self.label_gpar_picTti_min_5.setText(_translate("cebsGparForm", "大尺寸门限"))
        self.checkBox_gpar_vision_res_addup.setText(_translate("cebsGparForm", "输出图像叠加标定"))
        self.pushButton_ctrl_compl.setText(_translate("cebsGparForm", "设定完成"))
        self.groupBox_eng.setTitle(_translate("cebsGparForm", "工程模式命令"))
        self.textEdit_eng_input.setHtml(_translate("cebsGparForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Q01</p></body></html>"))
        self.pushButton_eng_send.setText(_translate("cebsGparForm", "发送"))
        self.pushButton_eng_clear.setText(_translate("cebsGparForm", "清除"))
        self.pushButton_ctrl_giveup.setText(_translate("cebsGparForm", "设定放弃"))

