# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cebsStestform.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cebsStestForm(object):
    def setupUi(self, cebsStestForm):
        cebsStestForm.setObjectName("cebsStestForm")
        cebsStestForm.resize(898, 615)
        self.pushButton_Stest_Start = QtWidgets.QPushButton(cebsStestForm)
        self.pushButton_Stest_Start.setGeometry(QtCore.QRect(40, 20, 121, 41))
        self.pushButton_Stest_Start.setObjectName("pushButton_Stest_Start")
        self.pushButton_Stest_Stop = QtWidgets.QPushButton(cebsStestForm)
        self.pushButton_Stest_Stop.setGeometry(QtCore.QRect(190, 20, 121, 41))
        self.pushButton_Stest_Stop.setObjectName("pushButton_Stest_Stop")
        self.textEdit_Stest_Trace_log = QtWidgets.QTextEdit(cebsStestForm)
        self.textEdit_Stest_Trace_log.setGeometry(QtCore.QRect(380, 30, 391, 501))
        self.textEdit_Stest_Trace_log.setObjectName("textEdit_Stest_Trace_log")
        self.label_Stest_print_log = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_print_log.setGeometry(QtCore.QRect(380, 10, 91, 16))
        self.label_Stest_print_log.setObjectName("label_Stest_print_log")
        self.label_Stest_serial = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_serial.setGeometry(QtCore.QRect(40, 100, 91, 16))
        self.label_Stest_serial.setObjectName("label_Stest_serial")
        self.label_Stest_camera = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_camera.setGeometry(QtCore.QRect(40, 130, 91, 16))
        self.label_Stest_camera.setObjectName("label_Stest_camera")
        self.label_Stest_moto_x = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_moto_x.setGeometry(QtCore.QRect(40, 160, 91, 16))
        self.label_Stest_moto_x.setObjectName("label_Stest_moto_x")
        self.label_Stest_moto_y = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_moto_y.setGeometry(QtCore.QRect(40, 190, 91, 16))
        self.label_Stest_moto_y.setObjectName("label_Stest_moto_y")
        self.label_Stest_calib = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_calib.setGeometry(QtCore.QRect(40, 220, 91, 16))
        self.label_Stest_calib.setObjectName("label_Stest_calib")
        self.label_Stest_batch_nbr = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_batch_nbr.setGeometry(QtCore.QRect(40, 250, 91, 16))
        self.label_Stest_batch_nbr.setObjectName("label_Stest_batch_nbr")
        self.label_Stest_batch_cfy_pic = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_batch_cfy_pic.setGeometry(QtCore.QRect(40, 280, 91, 16))
        self.label_Stest_batch_cfy_pic.setObjectName("label_Stest_batch_cfy_pic")
        self.label_Stest_hb = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_hb.setGeometry(QtCore.QRect(40, 400, 91, 16))
        self.label_Stest_hb.setObjectName("label_Stest_hb")
        self.lineEdit_Stest_batch_nbr = QtWidgets.QLineEdit(cebsStestForm)
        self.lineEdit_Stest_batch_nbr.setGeometry(QtCore.QRect(150, 250, 113, 20))
        self.lineEdit_Stest_batch_nbr.setObjectName("lineEdit_Stest_batch_nbr")
        self.lineEdit_Stest_batch_cfy_pic = QtWidgets.QLineEdit(cebsStestForm)
        self.lineEdit_Stest_batch_cfy_pic.setGeometry(QtCore.QRect(150, 280, 113, 20))
        self.lineEdit_Stest_batch_cfy_pic.setObjectName("lineEdit_Stest_batch_cfy_pic")
        self.lineEdit_Stest_hb = QtWidgets.QLineEdit(cebsStestForm)
        self.lineEdit_Stest_hb.setGeometry(QtCore.QRect(150, 400, 113, 20))
        self.lineEdit_Stest_hb.setObjectName("lineEdit_Stest_hb")
        self.checkBox_Stest_serial = QtWidgets.QCheckBox(cebsStestForm)
        self.checkBox_Stest_serial.setGeometry(QtCore.QRect(150, 100, 71, 16))
        self.checkBox_Stest_serial.setText("")
        self.checkBox_Stest_serial.setShortcut("")
        self.checkBox_Stest_serial.setCheckable(True)
        self.checkBox_Stest_serial.setChecked(False)
        self.checkBox_Stest_serial.setAutoRepeat(False)
        self.checkBox_Stest_serial.setAutoExclusive(False)
        self.checkBox_Stest_serial.setObjectName("checkBox_Stest_serial")
        self.checkBox_Stest_camera = QtWidgets.QCheckBox(cebsStestForm)
        self.checkBox_Stest_camera.setGeometry(QtCore.QRect(150, 130, 71, 16))
        self.checkBox_Stest_camera.setText("")
        self.checkBox_Stest_camera.setObjectName("checkBox_Stest_camera")
        self.checkBox_Stest_moto_x = QtWidgets.QCheckBox(cebsStestForm)
        self.checkBox_Stest_moto_x.setGeometry(QtCore.QRect(150, 160, 71, 16))
        self.checkBox_Stest_moto_x.setText("")
        self.checkBox_Stest_moto_x.setObjectName("checkBox_Stest_moto_x")
        self.checkBox_Stest_moto_y = QtWidgets.QCheckBox(cebsStestForm)
        self.checkBox_Stest_moto_y.setGeometry(QtCore.QRect(150, 190, 71, 16))
        self.checkBox_Stest_moto_y.setText("")
        self.checkBox_Stest_moto_y.setObjectName("checkBox_Stest_moto_y")
        self.checkBox_Stest_calib = QtWidgets.QCheckBox(cebsStestForm)
        self.checkBox_Stest_calib.setGeometry(QtCore.QRect(150, 220, 71, 16))
        self.checkBox_Stest_calib.setText("")
        self.checkBox_Stest_calib.setObjectName("checkBox_Stest_calib")
        self.pushButton_Stest_Stop_2 = QtWidgets.QPushButton(cebsStestForm)
        self.pushButton_Stest_Stop_2.setGeometry(QtCore.QRect(510, 540, 121, 41))
        self.pushButton_Stest_Stop_2.setObjectName("pushButton_Stest_Stop_2")
        self.pushButton_Stest_Stop_3 = QtWidgets.QPushButton(cebsStestForm)
        self.pushButton_Stest_Stop_3.setGeometry(QtCore.QRect(650, 540, 121, 41))
        self.pushButton_Stest_Stop_3.setObjectName("pushButton_Stest_Stop_3")
        self.lineEdit_Stest_batch_cfy_flu = QtWidgets.QLineEdit(cebsStestForm)
        self.lineEdit_Stest_batch_cfy_flu.setGeometry(QtCore.QRect(150, 310, 113, 20))
        self.lineEdit_Stest_batch_cfy_flu.setObjectName("lineEdit_Stest_batch_cfy_flu")
        self.label_Stest_batch_cfy_flu = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_batch_cfy_flu.setGeometry(QtCore.QRect(40, 310, 91, 16))
        self.label_Stest_batch_cfy_flu.setObjectName("label_Stest_batch_cfy_flu")
        self.label_Stest_cfy_flu_rem_cnt = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_cfy_flu_rem_cnt.setGeometry(QtCore.QRect(40, 370, 91, 16))
        self.label_Stest_cfy_flu_rem_cnt.setObjectName("label_Stest_cfy_flu_rem_cnt")
        self.lineEdit_Stest_cfy_pic_rem_cnt = QtWidgets.QLineEdit(cebsStestForm)
        self.lineEdit_Stest_cfy_pic_rem_cnt.setGeometry(QtCore.QRect(150, 340, 113, 20))
        self.lineEdit_Stest_cfy_pic_rem_cnt.setObjectName("lineEdit_Stest_cfy_pic_rem_cnt")
        self.label_Stest_cfy_pic_rem_cnt = QtWidgets.QLabel(cebsStestForm)
        self.label_Stest_cfy_pic_rem_cnt.setGeometry(QtCore.QRect(40, 340, 91, 16))
        self.label_Stest_cfy_pic_rem_cnt.setObjectName("label_Stest_cfy_pic_rem_cnt")
        self.lineEdit_Stest_cfy_flu_rem_cnt = QtWidgets.QLineEdit(cebsStestForm)
        self.lineEdit_Stest_cfy_flu_rem_cnt.setGeometry(QtCore.QRect(150, 370, 113, 20))
        self.lineEdit_Stest_cfy_flu_rem_cnt.setObjectName("lineEdit_Stest_cfy_flu_rem_cnt")

        self.retranslateUi(cebsStestForm)
        self.pushButton_Stest_Start.clicked.connect(cebsStestForm.slot_stest_start)
        self.pushButton_Stest_Stop.clicked.connect(cebsStestForm.slot_stest_stop)
        self.pushButton_Stest_Stop_2.clicked.connect(cebsStestForm.slot_stest_clear)
        self.pushButton_Stest_Stop_3.clicked.connect(cebsStestForm.slot_stest_compl)
        QtCore.QMetaObject.connectSlotsByName(cebsStestForm)

    def retranslateUi(self, cebsStestForm):
        _translate = QtCore.QCoreApplication.translate
        cebsStestForm.setWindowTitle(_translate("cebsStestForm", "自测自检"))
        self.pushButton_Stest_Start.setText(_translate("cebsStestForm", "自检开始"))
        self.pushButton_Stest_Stop.setText(_translate("cebsStestForm", "自检停止"))
        self.textEdit_Stest_Trace_log.setHtml(_translate("cebsStestForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">TRACE LOG</p></body></html>"))
        self.label_Stest_print_log.setText(_translate("cebsStestForm", "测试打印窗口"))
        self.label_Stest_serial.setText(_translate("cebsStestForm", "串口连接"))
        self.label_Stest_camera.setText(_translate("cebsStestForm", "摄像头连接"))
        self.label_Stest_moto_x.setText(_translate("cebsStestForm", "X轴马达运动"))
        self.label_Stest_moto_y.setText(_translate("cebsStestForm", "Y轴马达运动"))
        self.label_Stest_calib.setText(_translate("cebsStestForm", "校准正常与否"))
        self.label_Stest_batch_nbr.setText(_translate("cebsStestForm", "最新拍摄批次号"))
        self.label_Stest_batch_cfy_pic.setText(_translate("cebsStestForm", "白光识别批次号"))
        self.label_Stest_hb.setText(_translate("cebsStestForm", "板孔型号"))
        self.pushButton_Stest_Stop_2.setText(_translate("cebsStestForm", "清除"))
        self.pushButton_Stest_Stop_3.setText(_translate("cebsStestForm", "返回"))
        self.label_Stest_batch_cfy_flu.setText(_translate("cebsStestForm", "荧光识别批次号"))
        self.label_Stest_cfy_flu_rem_cnt.setText(_translate("cebsStestForm", "荧光剩余数量"))
        self.label_Stest_cfy_pic_rem_cnt.setText(_translate("cebsStestForm", "白光剩余数量"))

